- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt:
        state: installed
        update_cache: true
        pkg:
        - vim
        - emacs
        - tmux
        - htop
        - aptitude
        - haskell-stack
        - golang-go
