- hosts: localhost
  tasks:
  - name: Install packages
    become: true
    apt:
        state: present
        update_cache: true
        pkg:
        - vim
        - emacs
        - tmux
        - htop
        - aptitude
        - haskell-stack
        - golang-go
  - name: Stack packages
    command: stack install super-user-spark
